# Webscrape College BBall

In [2]:
import pandas as pd
import requests
import ssl

In [3]:
ssl._create_default_https_context = ssl._create_unverified_context

In [27]:
pd.read_html("https://basketball.realgm.com/ncaa/conferences/Big-12-Conference/3/players/2024", encoding='ISO-8859-1')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 194993: invalid start byte

Big 12

In [29]:
conference_dictionary = { "https://basketball.realgm.com/ncaa/conferences/America-East-Conference/18/players/2024":"AM_East", "https://basketball.realgm.com/ncaa/conferences/American-Athletic-Conference/4/players/2024":"American", "https://basketball.realgm.com/ncaa/conferences/Atlantic-10-Conference/10/players/2024":"A-10", "https://basketball.realgm.com/ncaa/conferences/Atlantic-Coast-Conference/1/players/2024":"ACC", "https://basketball.realgm.com/ncaa/conferences/Atlantic-Sun-Conference/19/players/2024":"A_Sun", "https://basketball.realgm.com/ncaa/conferences/Big-12-Conference/3/players/2024":"Big_12", "https://basketball.realgm.com/ncaa/conferences/Big-East-Conference/59/players/2024":"Big_East", "https://basketball.realgm.com/ncaa/conferences/Big-Sky-Conference/20/players/2024":"Big_Sky", "https://basketball.realgm.com/ncaa/conferences/Big-South-Conference/21/players/2024":"Big_South", "https://basketball.realgm.com/ncaa/conferences/Big-Ten-Conference/2/players/2024":"Big_10", "https://basketball.realgm.com/ncaa/conferences/Big-West-Conference/22/players/2024":"Big_West", "https://basketball.realgm.com/ncaa/conferences/Coastal-Athletic-Association/15/players/2024":"CAA", "https://basketball.realgm.com/ncaa/conferences/Conference-USA/9/players/2024":"C_USA", "https://basketball.realgm.com/ncaa/conferences/Horizon-League/12/players/2024":"Horizon", "https://basketball.realgm.com/ncaa/conferences/Ivy-League/14/players/2024":"Ivy", "https://basketball.realgm.com/ncaa/conferences/Metro-Atlantic-Athletic-Conference/17/players/2024":"MAAC", "https://basketball.realgm.com/ncaa/conferences/Mid-American-Conference/25/players/2024":"MAC", "https://basketball.realgm.com/ncaa/conferences/Mid-Eastern-Athletic-Conference/26/players/2024":"MEAC", "https://basketball.realgm.com/ncaa/conferences/Missouri-Valley-Conference/5/players/2024":"MVC", "https://basketball.realgm.com/ncaa/conferences/Mountain-West-Conference/6/players/2024":"MW", "https://basketball.realgm.com/ncaa/conferences/Northeast-Conference/27/players/2024":"NEC","https://basketball.realgm.com/ncaa/conferences/Ohio-Valley-Conference/16/players/2024":"OVC", "https://basketball.realgm.com/ncaa/conferences/Pacific-12-Conference/7/players/2024":"Pac_12","https://basketball.realgm.com/ncaa/conferences/Patriot-League/28/players/2024":"Patriot", "https://basketball.realgm.com/ncaa/conferences/Southeastern-Conference/8/players/2024":"SEC", "https://basketball.realgm.com/ncaa/conferences/Southern-Conference/29/players/2024":"Southern", "https://basketball.realgm.com/ncaa/conferences/Southwestern-Athletic-Conference/31/players/2024":"SWAC", "https://basketball.realgm.com/ncaa/conferences/Sun-Belt-Conference/33/players/2024":"Sun_Belt", "https://basketball.realgm.com/ncaa/conferences/The-Summit-League/32/players/2024":"Summit", "https://basketball.realgm.com/ncaa/conferences/West-Coast-Conference/11/players/2024":"WCC", "https://basketball.realgm.com/ncaa/conferences/Western-Athletic-Conference/13/players/2024":"WAC"}

In [52]:
def conference_to_csv(dict):
  conference_dataframes = []
  for k, v in dict.items():
      example = pd.read_html(k, encoding='ISO-8859-1')
      example_df = example[0]
      example_df.sort_values(by="School", inplace = True)
      conference_dataframes.append(example_df)
  return conference_dataframes

In [54]:
list_of_conference_dataframes = conference_to_csv(conference_dictionary)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/bs4/__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

In [55]:
pd.concat(list_of_conference_dataframes)

,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School
124,Sebastian Thomas,G,6-1,180.0,Albany,Jr,-,Providence (RI),Hoosac School
103,Aaron Reddish,GF,6-7,195.0,Albany,Jr,-,West Chester (PA),Pebblebrook High School
79,Zach Matulu,G,6-2,NaN,Albany,Fr,-,Latham (NY),Shaker High School
78,Amar'e Marshall,PG,6-4,207.0,Albany,So,-,Montclair (NJ),Roselle Catholic High School
77,Jack Margoupis,F,6-8,NaN,Albany,Fr,-,Sutton (MA),Cushing Academy
...,...,...,...,...,...,...,...,...,...
44,K'mani Doughty,SG,6-5,195.0,Utah Valley,Jr,-,Brooklyn (NY),Florida Preparatory Academy
108,Jaden McClanahan,PG,5-10,175.0,Utah Valley,Sr,"May 11, 2001",Richmond (CA),Salesian College Prep
157,Caleb Stone-Carrawell,G,6-7,210.0,Utah Valley,Sr,-,Concord (NC),Cox Mill High School
5,Peter Amakasu,G,6-4,195.0,Utah Valley,Fr,-,San Diego (CA),Lehi High School
125,Ethan Potter,F,6-8,205.0,Utah Valley,So,-,Layton (UT),Layton High School

In [42]:
conference_to_csv(conference_dictionary)

In [9]:
def conference_to_csv(url, conference):
  example = pd.read_html(url)
  example_df = example[0]
  example_df.sort_values(by="School", inplace = True)
  example_df.to_csv(conference + ".csv")

In [10]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/America-East-Conference/18/players/2024", "AM_East")

In [30]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/American-Athletic-Conference/4/players/2024", "American")

TypeError: conference_to_csv() takes 1 positional argument but 2 were given

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Atlantic-10-Conference/10/players/2024", "A-10")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Atlantic-Coast-Conference/1/players/2024", "ACC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Atlantic-Sun-Conference/19/players/2024", "A_Sun")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Big-12-Conference/3/players/2024", "Big_12")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Big-East-Conference/59/players/2024":"Big_East")
"https://basketball.realgm.com/ncaa/conferences/Big-East-Conference/59/players/2024":"Big_East",
"https://basketball.realgm.com/ncaa/conferences/Big-Sky-Conference/20/players/2024":"Big_Sky",
"https://basketball.realgm.com/ncaa/conferences/Big-South-Conference/21/players/2024":"Big_South",
"https://basketball.realgm.com/ncaa/conferences/Big-Ten-Conference/2/players/2024":"Big_10",
"https://basketball.realgm.com/ncaa/conferences/Big-West-Conference/22/players/2024":"Big_West",
"https://basketball.realgm.com/ncaa/conferences/Coastal-Athletic-Association/15/players/2024":"CAA",
"https://basketball.realgm.com/ncaa/conferences/Conference-USA/9/players/2024":"C_USA",
"https://basketball.realgm.com/ncaa/conferences/Horizon-League/12/players/2024":"Horizon",
"https://basketball.realgm.com/ncaa/conferences/Ivy-League/14/players/2024":"Ivy",
"https://basketball.realgm.com/ncaa/conferences/Metro-Atlantic-Athletic-Conference/17/players/2024":"MAAC",
"https://basketball.realgm.com/ncaa/conferences/Mid-American-Conference/25/players/2024":"MAC",
"https://basketball.realgm.com/ncaa/conferences/Mid-Eastern-Athletic-Conference/26/players/2024":"MEAC",
"https://basketball.realgm.com/ncaa/conferences/Missouri-Valley-Conference/5/players/2024":"MVC",
"https://basketball.realgm.com/ncaa/conferences/Mountain-West-Conference/6/players/2024":"MW",
"https://basketball.realgm.com/ncaa/conferences/Northeast-Conference/27/players/2024":"NEC",
"https://basketball.realgm.com/ncaa/conferences/Ohio-Valley-Conference/16/players/2024":"OVC",
"https://basketball.realgm.com/ncaa/conferences/Pacific-12-Conference/7/players/2024":"Pac_12",
"https://basketball.realgm.com/ncaa/conferences/Patriot-League/28/players/2024":"Patriot",
"https://basketball.realgm.com/ncaa/conferences/Southeastern-Conference/8/players/2024":"SEC",
"https://basketball.realgm.com/ncaa/conferences/Southern-Conference/29/players/2024":"Southern",
"https://basketball.realgm.com/ncaa/conferences/Southwestern-Athletic-Conference/31/players/2024":"SWAC",
"https://basketball.realgm.com/ncaa/conferences/Sun-Belt-Conference/33/players/2024":"Sun_Belt",
"https://basketball.realgm.com/ncaa/conferences/The-Summit-League/32/players/2024":"Summit",
"https://basketball.realgm.com/ncaa/conferences/West-Coast-Conference/11/players/2024":"WCC",
"https://basketball.realgm.com/ncaa/conferences/Western-Athletic-Conference/13/players/2024":"WAC"

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Big-Sky-Conference/20/players/2024", "Big_Sky")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Big-South-Conference/21/players/2024", "Big_South")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Big-Ten-Conference/2/players/2024", "Big_10")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Big-West-Conference/22/players/2024", "Big_West")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Coastal-Athletic-Association/15/players/2024", "CAA")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Conference-USA/9/players/2024", "C_USA")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Horizon-League/12/players/2024", "Horizon")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Ivy-League/14/players/2024", "Ivy")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Metro-Atlantic-Athletic-Conference/17/players/2024", "MAAC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Mid-American-Conference/25/players/2024", "MAC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Mid-Eastern-Athletic-Conference/26/players/2024", "MEAC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Missouri-Valley-Conference/5/players/2024", "MVC")
"https://basketball.realgm.com/ncaa/conferences/Missouri-Valley-Conference/5/players/2024", "MVC"
"https://basketball.realgm.com/ncaa/conferences/Mountain-West-Conference/6/players/2024", "MW"
"https://basketball.realgm.com/ncaa/conferences/Northeast-Conference/27/players/2024", "NEC"
"https://basketball.realgm.com/ncaa/conferences/Ohio-Valley-Conference/16/players/2024", "OVC"
"https://basketball.realgm.com/ncaa/conferences/Pacific-12-Conference/7/players/2024", "Pac_12"
"https://basketball.realgm.com/ncaa/conferences/Patriot-League/28/players/2024", "Patriot"
"https://basketball.realgm.com/ncaa/conferences/Southeastern-Conference/8/players/2024", "SEC"
"https://basketball.realgm.com/ncaa/conferences/Southern-Conference/29/players/2024", "Southern"
"https://basketball.realgm.com/ncaa/conferences/Southwestern-Athletic-Conference/31/players/2024", "SWAC"
"https://basketball.realgm.com/ncaa/conferences/Sun-Belt-Conference/33/players/2024", "Sun_Belt"
"https://basketball.realgm.com/ncaa/conferences/The-Summit-League/32/players/2024", "Summit"
"https://basketball.realgm.com/ncaa/conferences/West-Coast-Conference/11/players/2024", "WCC"
"https://basketball.realgm.com/ncaa/conferences/Western-Athletic-Conference/13/players/2024", "WAC"

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Mountain-West-Conference/6/players/2024", "MW")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Northeast-Conference/27/players/2024", "NEC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Ohio-Valley-Conference/16/players/2024", "OVC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Pacific-12-Conference/7/players/2024", "Pac_12")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Patriot-League/28/players/2024", "Patriot")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Southeastern-Conference/8/players/2024", "SEC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Southern-Conference/29/players/2024", "Southern")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Southland-Conference/30/players/2024", "Southland")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Southwestern-Athletic-Conference/31/players/2024", "SWAC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Sun-Belt-Conference/33/players/2024", "Sun_Belt")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/The-Summit-League/32/players/2024", "Summit")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/West-Coast-Conference/11/players/2024", "WCC")

In [ ]:
conference_to_csv("https://basketball.realgm.com/ncaa/conferences/Western-Athletic-Conference/13/players/2024", "WAC")

In [ ]:
def conference_major(args*, level = "Mid"):
  for each

Opening Each CSV as DataFrame

Add Conference Label

In [ ]:
A_10_df = pd.read_csv("A-10.csv")

In [ ]:
A_10_df["Conference"] = "A-10"

In [ ]:
A_10_df.head()

,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference
0,0,Hunter Adam,F,6-7,205.0,Davidson,Fr,"Sep 29, 2004",Christchurch,Christ's College,A-10
1,211,Achile Spadone,G,6-4,185.0,Davidson,So,"Sep 24, 2003",Geneva,St. Thomas More School,A-10
2,207,Chris Sosnik,G,6-2,180.0,Davidson,Sr,"Apr 16, 2002",Washington (DC),St. Albans School,A-10
3,201,David Skogman,PF,6-10,235.0,Davidson,Sr,"Feb 10, 2001",Waukesha (WI),Waukesha West High School,A-10
4,195,Rikus Schulte,PF,6-9,235.0,Davidson,Fr,"Jun 1, 2004",Munster,NaN,A-10

In [ ]:
A_10_df.to_csv("A-10.csv")

In [ ]:
def add_conference_column(CSV_file):
  holder_df = pd.read_csv(CSV_file)
  conference_name = CSV_file.split(".")[0]
  holder_df["Conference"] = conference_name
  holder_df.to_csv(CSV_file)

In [ ]:
add_conference_column("WCC.csv")

High-Major:
* ACC
* PAC 12
* SEC
* Big 10
* Big 12
* Big East



Mid-Major:
* A-10
* American Athletic Conference
* CAA
* Conference-USA
* Horizon
* MAC
* Missouri Valley
* Mountain West
* WCC
* WAC

Low-Major:
* American East
* Ivy League
* Big South
* NEC
* Patriot League
* Southern Conference
* Southwestern Athletic Conference
* Missouri Valley
* Atlantic Sun
* Ohio Valley
* MAAC
* SWAC
* Big West
* Sun Belt
* Big Sky
* MEAC
* Southland Conference
* The Summit League


Based on:
https://www.researchgate.net/figure/List-of-NCAA-Division-I-Basketball-Conferences-by-Classification_tbl1_254415765

High-Major:
* ACC
* PAC 12
* SEC
* Big 10
* Big 12
* Big East

In [ ]:
acc_df = pd.read_csv("ACC.csv")
pac12_df = pd.read_csv("Pac_12.csv")
sec_df = pd.read_csv("SEC.csv")
big10_df = pd.read_csv("Big_10.csv")
big12_df = pd.read_csv("Big_12.csv")
big_east_df = pd.read_csv("Big_East.csv")

In [ ]:
high_major_df = pd.concat([acc_df, pac12_df, sec_df, big10_df, big12_df, big_east_df])

In [ ]:
high_major_df.Conference.value_counts()

ACC         244
SEC         234
Big_10      223
Big_12      217
Pac_12      202
Big_East    172
Name: Conference, dtype: int64

In [ ]:
high_major_df.head(20)

,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference
0,0,175,Quinten Post,C,7-0,250.0,Boston College,Sr,"Mar 21, 2000",Amsterdam,NaN,ACC
1,1,113,Chas Kelley III,G,6-5,180.0,Boston College,So,-,Houston (TX),Phelps Prep,ACC
2,2,82,"Claudell Harris, Jr.",GF,6-3,190.0,Boston College,Jr,-,Hahnville (LA),Hahnville High School,ACC
3,3,242,Jaeden Zackery,G,6-2,215.0,Boston College,Jr,-,Salem (WI),Westosha Central High School,ACC
4,4,211,Elijah Strong,F,6-8,245.0,Boston College,Fr,-,Charlotte (NC),Myers Park High School,ACC
5,5,171,Fred Payne,G,6-2,170.0,Boston College,Fr,-,Grambling (LA),Legacy the School of Sport Sciences,ACC
6,6,102,Asher Jackson,G,6-5,205.0,Boston College,Fr,-,Mundelein (IL),Carmel Catholic High School,ACC
7,7,51,Jack Di Donna,G,6-0,185.0,Boston College,Fr,-,Boca Raton (FL),Saint Andrew's School,ACC
8,8,79,"Donald Hand, Jr.",GF,6-5,195.0,Boston College,Fr,-,Virginia Beach (VA),Landstown High School,ACC
9,9,204,Ethan Soares,GF,6-4,225.0,Boston College,Fr,-,Houston (TX),Memorial High School,ACC
10,10,141,Armani Mighty,C,6-10,225.0,Boston College,So,-,Thornhill,United Scholastic Academy,ACC
11,11,128,Mason Madsen,G,6-4,195.0,Boston College,Sr,"May 1, 2001",Rochester (MN),Mayo High School,ACC
12,12,4,Abe Atiyeh,G,6-0,195.0,Boston College,Sr,-,Bethlehem (PA),Moravian Academy,ACC
13,13,83,Jayden Hastings,FC,6-9,225.0,Boston College,Fr,-,Orlando (FL),IMG Academy,ACC
14,14,2,Prince Aligbe,F,6-7,225.0,Boston College,So,-,Minneapolis (MN),Minnehaha Academy,ACC
15,15,137,Devin McGlockton,F,6-7,215.0,Boston College,Jr,-,Cumming (GA),South Forsyth High School,ACC
16,16,35,Jack Clark,F,6-8,200.0,Clemson,Sr,"Feb 14, 2000",Wyncote (PA),Cheltenham High School,ACC
17,17,78,P.J. Hall,PF,6-10,245.0,Clemson,Sr,"Feb 21, 2002",Roebuck (SC),Dorman High School,ACC
18,18,96,Chase Hunter,SG,6-4,204.0,Clemson,Sr,"Apr 8, 2001",Atlanta (GA),Westlake High School,ACC
19,19,216,Asa Thomas,F,6-7,185.0,Clemson,Fr,-,Lake Forest (IL),Lake Forest High School,ACC

In [ ]:
high_major_df.to_csv("High_Major.csv")

Mid-Major:
* A-10
* American Athletic Conference
* CAA
* Conference-USA
* Horizon
* MAC
* Missouri Valley
* Mountain West
* WCC
* WAC

In [ ]:
a10_df = pd.read_csv("A-10.csv")
aac_df = pd.read_csv("American.csv")
caa_df = pd.read_csv("CAA.csv")
c_usa_df = pd.read_csv("C_USA.csv")
horizon_df = pd.read_csv("Horizon.csv")
mac_df = pd.read_csv("MAC.csv")
mvc_df = pd.read_csv("MVC.csv")
mwc_df = pd.read_csv("MWC.csv")
wcc_df = pd.read_csv("WCC.csv")
wac_df = pd.read_csv("WAC.csv")

In [ ]:
mwc_df["Conference"] = "MWC"

In [ ]:
mid_major_df = pd.concat([a10_df, aac_df, caa_df, c_usa_df, horizon_df, mac_df, mvc_df, mwc_df, wcc_df, wac_df])

In [ ]:
mid_major_df.Conference.value_counts()

A-10        242
CAA         234
American    216
MVC         184
WAC         181
MWC         180
MAC         177
Horizon     169
C_USA       139
WCC         139
Name: Conference, dtype: int64

In [ ]:
#print(mid_major_df.to_string())

In [ ]:
mid_major_df.to_csv("Mid_Major.csv")

Low-Major:
* American East
* Ivy League
* Big South
* NEC
* Patriot League
* Southern Conference
* Missouri Valley
* Atlantic Sun
* Ohio Valley
* MAAC
* SWAC
* Big West
* Sun Belt
* Big Sky
* MEAC
* Southland Conference
* The Summit League

#### Flagging: Accidentally Included Missouri Valley Conference in both Mid & Low majors at first

####Has been corrected by deleting MVC Low rows in Excel

In [ ]:
AM_East_df = pd.read_csv("AM_East.csv")
Ivy_df = pd.read_csv("Ivy.csv")
Big_South_df = pd.read_csv("Big_South.csv")
NEC_df = pd.read_csv("NEC.csv")
Patriot_df = pd.read_csv("Patriot.csv")
Southern_df = pd.read_csv("Southern.csv")
SWAC_df = pd.read_csv("SWAC.csv")
MVC_df = pd.read_csv("MVC.csv")
A_Sun_df = pd.read_csv("A_Sun.csv")
OVC_df = pd.read_csv("OVC.csv")
MAAC_df = pd.read_csv("MAAC.csv")
Big_West_df = pd.read_csv("Big_West.csv")
Sun_Belt_df = pd.read_csv("Sun_Belt.csv")
Big_Sky_df = pd.read_csv("Big_Sky.csv")
MEAC_df = pd.read_csv("MEAC.csv")
Southland_df = pd.read_csv("Southland.csv")
Summit_df = pd.read_csv("Summit.csv")

In [ ]:
low_major_df = pd.concat([AM_East_df,Ivy_df,Big_South_df,NEC_df,Patriot_df,Southern_df,SWAC_df,MVC_df,A_Sun_df,OVC_df,MAAC_df,Big_West_df,Sun_Belt_df,Big_Sky_df,MEAC_df,Southland_df,Summit_df])

In [ ]:
#print(low_major_df.to_string())

In [ ]:
low_major_df.to_csv("Low_Major.csv")

Adding Major Column

In [ ]:
high_major_df["Major"] = "High"
mid_major_df["Major"] = "Mid"
low_major_df["Major"] = "Low"

In [ ]:
all_conferences_df = pd.concat([high_major_df, mid_major_df, low_major_df])

In [ ]:
all_conferences_df.head()

,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major
0,0.0,175,Quinten Post,C,7-0,250.0,Boston College,Sr,"Mar 21, 2000",Amsterdam,NaN,ACC,High
1,1.0,113,Chas Kelley III,G,6-5,180.0,Boston College,So,-,Houston (TX),Phelps Prep,ACC,High
2,2.0,82,"Claudell Harris, Jr.",GF,6-3,190.0,Boston College,Jr,-,Hahnville (LA),Hahnville High School,ACC,High
3,3.0,242,Jaeden Zackery,G,6-2,215.0,Boston College,Jr,-,Salem (WI),Westosha Central High School,ACC,High
4,4.0,211,Elijah Strong,F,6-8,245.0,Boston College,Fr,-,Charlotte (NC),Myers Park High School,ACC,High

In [ ]:
all_conferences_df.Major.value_counts(ascending = True)

High    1292
Mid     1861
Low     2808
Name: Major, dtype: int64

In [ ]:
all_conferences_df.to_csv("All_Conferences.csv")

In [ ]:
46+39+24+4+3

116

In [ ]:
all_conferences_df[(all_conferences_df["Birth City"] == "New Rochelle (NY)")]

,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major
48,48.0,96,Kobe Jerome,G,6-4,190.0,Delaware,So,-,New Rochelle (NY),Blue Ridge School,CAA,Mid
80,80.0,95,Promise Opurum,F,6-7,215.0,New Hampshire,Fr,-,New Rochelle (NY),Woodstock Academy,AM_East,Low

In [ ]:
#print(all_conferences_df["Birth City"].value_counts().to_string())

In [ ]:
all_conferences_df.head()

,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major
0,0.0,175,Quinten Post,C,7-0,250.0,Boston College,Sr,"Mar 21, 2000",Amsterdam,NaN,ACC,High
1,1.0,113,Chas Kelley III,G,6-5,180.0,Boston College,So,-,Houston (TX),Phelps Prep,ACC,High
2,2.0,82,"Claudell Harris, Jr.",GF,6-3,190.0,Boston College,Jr,-,Hahnville (LA),Hahnville High School,ACC,High
3,3.0,242,Jaeden Zackery,G,6-2,215.0,Boston College,Jr,-,Salem (WI),Westosha Central High School,ACC,High
4,4.0,211,Elijah Strong,F,6-8,245.0,Boston College,Fr,-,Charlotte (NC),Myers Park High School,ACC,High

Replace - with 0

5011
604
6011
701

If length of string is 4, then remove first 0


511
604
701


Make it 6' Based

511 becomes 599
701 becomes 613

In [ ]:
all_conferences_df.HT = all_conferences_df.HT.astype("string")

In [ ]:
all_conferences_df.iloc[504, 4] = "6-4"

'6-4'

In [ ]:
all_conferences_df.iloc[3565, 4] = "5-11"

In [ ]:
all_conferences_df.HT = all_conferences_df.HT.apply(lambda x: x.replace("-", "0"))

In [ ]:
all_conferences_df.HT = all_conferences_df.HT.apply(lambda x: x.replace("0", "") if len(x) == 4 else x)

In [ ]:
all_conferences_df.HT = all_conferences_df.HT.apply(lambda x: x+"0" if len(x) == 2 else x)

In [ ]:
all_conferences_df.HT = all_conferences_df.HT.apply(lambda x: int(x))

In [ ]:
all_conferences_df_copy = all_conferences_df

In [ ]:
all_conferences_df.head()

,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major
0,0.0,175,Quinten Post,C,612,250.0,Boston College,Sr,"Mar 21, 2000",Amsterdam,NaN,ACC,High
1,1.0,113,Chas Kelley III,G,605,180.0,Boston College,So,-,Houston (TX),Phelps Prep,ACC,High
2,2.0,82,"Claudell Harris, Jr.",GF,603,190.0,Boston College,Jr,-,Hahnville (LA),Hahnville High School,ACC,High
3,3.0,242,Jaeden Zackery,G,602,215.0,Boston College,Jr,-,Salem (WI),Westosha Central High School,ACC,High
4,4.0,211,Elijah Strong,F,608,245.0,Boston College,Fr,-,Charlotte (NC),Myers Park High School,ACC,High

In [ ]:
all_conferences_df[(all_conferences_df.HT >= 700)].HT.value_counts()

700    91
701    32
702    13
703     5
704     2
705     2
Name: HT, dtype: int64

In [ ]:
all_conferences_df.HT = all_conferences_df.HT.apply(lambda x: 612 if x == 700 else (613 if x == 701 else (614 if x == 702 else (615 if x ==703 else(616 if x == 704 else(617 if x == 705 else x))))))

In [ ]:
all_conferences_df[(all_conferences_df.HT < 600)].HT.value_counts()

511    104
510     97
509     25
508     24
507      2
505      1
Name: HT, dtype: int64

In [ ]:
all_conferences_df.HT = all_conferences_df.HT.apply(lambda x: 599 if x == 511 else (598 if x == 510 else (597 if x == 509 else (596 if x ==508 else(595 if x == 507 else(593 if x == 505 else x))))))

In [ ]:
all_conferences_df[(all_conferences_df.HT < 600)]

,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major
38,38.0,94,Spencer Hubbard,G,596,157.0,Duke,Sr,"Apr 30, 2001",Studio City (CA),Harvard-Westlake School,ACC,High
60,60.0,202,Jason Simpson,G,598,155.0,Florida State,Jr,"Aug 24, 2002",West Palm Beach (FL),Montverde Academy,ACC,High
127,127.0,111,K.J. Keatts,G,598,165.0,NC State,So,-,Cary (NC),Broughton High School,ACC,High
168,168.0,131,K.J. Marshall,PG,598,175.0,Pittsburgh,Sr,"Aug 16, 2000",Fayetteville (AR),Trinity Christian,ACC,High
179,179.0,193,Niko Ruffin,G,598,170.0,Syracuse,Jr,-,Cresskill (NJ),Paramus Catholic High School,ACC,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,110.0,34,Braelon Bush,G,596,155.0,Northwestern State,Sr,-,Silsbee (TX),Silsbee High School,Southland,Low
116,116.0,52,Roscoe Eastmond,G,597,150.0,Southeastern Louisiana,Sr,"Feb 2, 2001",Marietta (GA),Joseph Wheeler High School,Southland,Low
126,126.0,108,Carlos Paez,PG,598,180.0,Southeastern Louisiana,Sr,"Jan 6, 2000",Carabobo,Sunrise Christian Academy,Southland,Low
64,64.0,83,Elijah Lawrence,G,599,160.0,Oral Roberts,Jr,-,Bellaire (TX),Bellaire High School,Summit,Low
124,124.0,135,Hayden Tibbits,G,599,165.0,St. Thomas-Minnesota,Fr,-,Medina (MN),Wayzata High School,Summit,Low

In [ ]:
#print(all_conferences_df.HT.to_string())

In [ ]:
all_conferences_df.to_csv("All_Conferences.csv")

# Average Height in D1 is 6'5", Median is also 6'5"

75% of players are over 6'3"

In [ ]:
all_conferences_df.HT.describe()

count    5777.000000
mean      605.193180
std         3.441448
min       593.000000
25%       603.000000
50%       605.000000
75%       608.000000
max       617.000000
Name: HT, dtype: float64

# Adding Home State

In [ ]:
all_conferences_df = pd.read_csv("All_Conferences_Updated.csv")

In [ ]:
all_conferences_df.to_csv("All_Conferences_Updated_w_State.csv")

In [ ]:
all_conferences_df["Birth City"] = all_conferences_df["Birth City"].astype("string")

In [ ]:
all_conferences_df["Birth City"].fillna("Not_Available", inplace=True)

In [ ]:
#print(all_conferences_df["Birth City"].to_string())

0                        Amsterdam
1                     Houston (TX)
2                   Hahnville (LA)
3                       Salem (WI)
4                   Charlotte (NC)
5                   Grambling (LA)
6                   Mundelein (IL)
7                  Boca Raton (FL)
8              Virginia Beach (VA)
9                     Houston (TX)
10                       Thornhill
11                  Rochester (MN)
12                  Bethlehem (PA)
13                    Orlando (FL)
14                Minneapolis (MN)
15                    Cumming (GA)
16                    Wyncote (PA)
17                    Roebuck (SC)
18                    Atlanta (GA)
19                Lake Forest (IL)
20                    Atlanta (GA)
21               Floyds Knobs (IN)
22                   Newburgh (IN)
23                 Charleston (SC)
24                 Glen Falls (NY)
25                     Dayton (OH)
26                    Clemson (SC)
27                    Grayson (GA)
28                 Loganville (GA)
29                          Bergen
30                   Columbia (SC)
31                    Suwanee (GA)
32                          Sydney
33                  Yorkville (IL)
34                 Shrewsbury (MA)
35                  Charlotte (NC)
36                     Corona (CA)
37                Yanceyville (NC)
38                Studio City (CA)
39                   Leesburg (VA)
40                 Middletown (NY)
41                        Montreal
42              San Francisco (CA)
43                        Istanbul
44                    Orlando (FL)
45                   Somerset (NJ)
46                    Lansing (KS)
47                Centerville (OH)
48                  St. Louis (MO)
49                 Greensboro (NC)
50                           Palma
51                    Jupiter (FL)
52               Fayetteville (NC)
53                      Arden (NC)
54                      Tampa (FL)
55                    Memphis (TN)
56                   Clermont (FL)
57                     Milton (GA)
58                       Serekunda
59                      Plano (TX)
60            West Palm Beach (FL)
61                    Trenton (NJ)
62                       King (NC)
63                    Jericho (VT)
64               Philadelphia (PA)
65                    Windsor (CT)
66            Fort Washington (MD)
67                 Clearwater (FL)
68                  Goldsboro (NC)
69                   Norcross (GA)
70                     Newnan (GA)
71                          M'Bour
72             Stone Mountain (GA)
73                    Phoenix (AZ)
74                    Houston (TX)
75                   Callahan (FL)
76                   Woodside (CA)
77                           Manly
78                         Conakry
79                         Toronto
80                         Conakry
81                 Louisville (KY)
82                           Accra
83                      Macon (GA)
84                    Atlanta (GA)
85                     Apopka (FL)
86                     Newark (NJ)
87                  Bardstown (KY)
88                Clarksville (TN)
89                  Milwaukee (WI)
90                  Calabasas (CA)
91           Rancho Cucamonga (CA)
92                 Charleston (SC)
93                  Milwaukee (WI)
94                           Lagos
95                  Riverside (CA)
96                       Gary (IN)
97                 Louisville (KY)
98                Los Angeles (CA)
99                Cherry Hill (NJ)
100                    Austin (TX)
101                    Milton (GA)
102              Philadelphia (PA)
103                Washington (DC)
104                          Lille
105                    Naples (FL)
106               Tinley Park (IL)
107                     Miami (FL)
108                  Ossining (NY)
109              Indianapolis (IN)
110                     Bluefields
111                        Toronto
112                        Monthey
113              Chesterfield (VA)
114                Plant City (FL)
115                  Lakeland (FL)
116           Fort Lauderdale (FL)
117                  Bessemer (AL)
118                   Mineola (NY)
119                Reidsville (NC)
120                  Creedmor (NC)
121                Washington (DC)
122                 Rock Hill (SC)
123                   Raleigh (NC)
124              Indianapolis (IN)
125                      Cary (NC)
126                          Paris
127                      Cary (NC)
128                      Cary (NC)
129                  New York (NY)
130                     Maidenhead
131              Huntersville (NC)
132                  La Porte (IN)
133           Menomonee Falls (WI)
134                      Gary (IN)
135                Greensboro (NC)
136               San Antonio (TX)
137                  Richmond (VA)
138                    Dallas (TX)
139                 Charlotte (NC)
140               West Orange (NJ)
141                Cookeville (TN)
142              White Plains (NY)
143                    Owasso (OK)
144                Zionsville (IN)
145               Centerville (OH)
146                  Franklin (MI)
147                     Miami (FL)
148         Ponte Vedra Beach (FL)
149              Indianapolis (IN)
150              San Clemente (CA)
151                   Oradell (NJ)
152                South Bend (IN)
153                 Mishawaka (IN)
154                 San Diego (CA)
155                South Bend (IN)
156                 Englewood (CO)
157                 Macedonia (OH)
158             State College (PA)
159              McKees Rocks (PA)
160                 Baltimore (MD)
161         Santa Cruz de Tenerife
162         Santa Cruz de Tenerife
163               Wilkinsburg (PA)
164                 Cleveland (OH)
165             Winston-Salem (NC)
166                       Helsinki
167                          Dakar
168              Fayetteville (AR)
169              Fayetteville (NC)
170             Daytona Beach (FL)
171                      Erie (PA)
172                Washington (DC)
173             Missouri City (TX)
174              Philadelphia (PA)
175                     Bronx (NY)
176                Gettysburg (PA)
177                    Newark (NJ)
178             Baldwinsville (NY)
179                 Cresskill (NJ)
180           Fort Washington (MD)
181                Sunderland (MA)
182           Charlottesville (VA)
183                  Culpeper (VA)
184                    Albany (NY)
185                   Katonah (NY)
186                Washington (PA)
187                   Concord (CA)
188                   Potomac (MD)
189          Plymouth Meeting (PA)
190                 Blue Bell (PA)
191                  Brooklyn (NY)
192                 Milwaukee (WI)
193                    Hayden (ID)
194                    Boston (MA)
195                  Brooklyn (NY)
196                 Milwaukee (WI)
197                      Poca (WV)
198                    Fulton (MD)
199                       Auckland
200                Brookville (NY)
201               Jersey City (NJ)
202                 Milwaukee (WI)
203                 Lynchburg (VA)
204                   Spokane (WA)
205            Peachtree City (GA)
206                Washington (DC)
207            Virginia Beach (VA)
208                Burlington (NC)
209                  Richmond (VA)
210                    Edmond (OK)
211                 Charlotte (NC)
212              Cartersville (GA)
213                 Woodstock (VA)
214                  Bethesda (MD)
215                Greensboro (NC)
216                   Clinton (MD)
217               Gainesville (FL)
218                Washington (DC)
219                  Richmond (VA)
220                   Roanoke (VA)
221                    Waxhaw (NC)
222                 Rock Hill (SC)
223                   Orlando (FL)
224                    Elkton (VA)
225                        Reading
226                        Beijing
227                   Chicago (IL)
228                     Omaha (NE)
229                      Skovlunde
230           Highlands Ranch (CO)
231                    Easton (PA)
232                   Hialeah (FL)
233             Winston-Salem (NC)
234                     Bixby (OK)
235                  Richmond (VA)
236              West Chester (PA)
237                 San Diego (CA)
238                          Genoa
239                    Parker (CO)
240                 Mahtomedi (MN)
241              Gaithersburg (MD)
242                   Chicago (IL)
243                       Worthing
0                     Oakland (CA)
1                       Granollers
2                     Suwanee (GA)
3                          Tallinn
4                           Kaunas
5                   Rochester (NY)
6                     Ontario (CA)
7                         Belgrade
8                           Oxford
9                      Tucson (AZ)
10                  St. Louis (MO)
11                          Kaunas
12                           Nacka
13                    Gilbert (AZ)
14                       Koulikoro
15                Santa Maria (CA)
16                    El Paso (TX)
17                     Tucson (AZ)
18                  Ypsilanti (MI)
19                      Tempe (AZ)
20                 Scottsdale (AZ)
21                     Dayton (OH)
22                   La Porte (IN)
23                       Brantford
24                     Toledo (OH)
25                   Brooklyn (NY)
26                     Peoria (IL)
27                         Toronto
28                  Cleveland (OH)
29                 New Canaan (CT)
30                Los Angeles (CA)
31            Shawnee Mission (KS)
32                 Middletown (NY)
33               Mount Juliet (TN)
34                    Gilbert (AZ)
35     Rancho Santa Margarita (CA)
36        San Juan Capistrano (CA)
37                        Richmond
38                     Herceg Novi
39                   Piedmont (CA)
40                  Santa Ana (CA)
41                           Lagos
42                 Northridge (CA)
43                    Chicago (IL)
44              San Francisco (CA)
45                 Walkertown (NC)
46             Woodland Hills (CA)
47               Huntersville (NC)
48                   Temecula (CA)
49                  Riverside (CA)
50                     Aurora (CO)
51                      Plano (TX)
52                  Charlotte (NC)
53                 New Canaan (CT)
54                 Saint Paul (MN)
55                       Reno (NV)
56                       Katy (TX)
57          Greenwood Village (CO)
58                     Dallas (TX)
59                   Superior (CO)
60                  Littleton (CO)
61                     Salida (CO)
62                           Dakar
63                 Menlo Park (CA)
64                    Vallejo (CA)
65                   Chandler (AZ)
66                    Raleigh (NC)
67                Los Angeles (CA)
68                 West Hills (CA)
69                    Lincoln (NE)
70                          Munich
71                          Lleida
72                        Montreal
73              Central Point (OR)
74                   Not_Available
75                 Fort Myers (FL)
76                   Not_Available
77                  West Linn (OR)
78                   Portland (OR)
79                Los Angeles (CA)
80                 Titusville (FL)
81                  Baltimore (MD)
82                Wilsonville (OR)
83                    Mauldin (SC)
84                          Bamako
85                   De Beque (CO)
86                          Bamako
87                    Houston (TX)
88               East Chicago (IN)
89                     Keizer (OR)
90                   Valencia (CA)
91                 Bellingham (WA)
92                   Tualatin (OR)
93                 Alpharetta (GA)
94                       Coquitlam
95                        Augsburg
96                  Kennewick (WA)
97               Indianapolis (IN)
98                            Juba
99           San Miguel de Tucuman
100                Ellensburg (WA)
101                Northridge (CA)
102                   Spokane (WA)
103                      Napa (CA)
104                    Quebec City
105                          Paris
106                   Alameda (CA)
107                   Thessaloniki
108                     Omaha (NE)
109                   Coppell (TX)
110                 Rockville (MD)
111                  San Jose (CA)
112                  Woodbury (MN)
113                 San Pedro (CA)
114           Shawnee Mission (KS)
115                   Salinas (CA)
116                  Lakewood (OH)
117                Alpharetta (GA)
118                 San Diego (CA)
119                   Andover (MA)
120               Los Angeles (CA)
121                   Jackson (MS)
122                    Corona (CA)
123                       Zaragoza
124                          Lagos
125                  Not_Available
126                  Marlboro (NJ)
127                   Chicago (IL)
128               Los Angeles (CA)
129          Long Island City (NY)
130                        Domzale
131                       Belgrade
132                 Las Vegas (NV)
133                 Las Vegas (NV)
134                          Bursa
135                  Glendale (CA)
136                 San Diego (CA)
137                  Marietta (GA)
138             Newport Beach (CA)
139                  Torrance (CA)
140                Waynesboro (GA)
141                Chatsworth (CA)
142                  Marietta (GA)
143                  Glendale (WI)
144                      Toowoomba
145               Los Angeles (CA)
146                         Munich
147               Los Angeles (CA)
148                Sacramento (CA)
149                 Cleveland (OH)
150                    Lynden (WA)
151                       Belgrade
152              South Jordan (UT)
153                     Provo (UT)
154                Loganville (GA)
155                Saint Paul (MN)
156                Sacramento (CA)
157                       Istanbul
158                          Lagos
159                     Provo (UT)
160                       Montreal
161                 Southlake (TX)
162                Chabet el Ameur
163                 Rochester (MN)
164                         Taipei
165                  Missoula (MT)
166                         Bamako
167                 Santa Ana (CA)
168                Fort Wayne (IN)
169                  Beaumont (TX)
170                   Seattle (WA)
171                        Yaounde
172                   Gilbert (AZ)
173                Gig Harbor (WA)
174                    Layton (UT)
175                          Lagos
176         Peapack-Gladstone (NJ)
177              Santa Monica (CA)
178                  Oak Park (CA)
179                      Reno (NV)
180                 Riverside (CA)
181                   Houston (TX)
182                       Ngaliema
183                   Seattle (WA)
184                Sacramento (CA)
185               Bolingbrook (IL)
186                     Boise (ID)
187                          Lagos
188                 Sunshine Coast
189               San Anselmo (CA)
190                   Spokane (WA)
191                    Tyrone (GA)
192                   Olympia (WA)
193                Mill Creek (WA)
194                       Mulhouse
195                         Skopje
196                Snoqualmie (WA)
197                  Spanaway (WA)
198                  New York (NY)
199                     Aspen (CO)
200                   Seattle (WA)
201                     Aspen (CO)
0                       Elgin (IL)
1                     Orlando (FL)
2                    Woodbury (NJ)
3                           Bamako
4                      Dallas (TX)
5                    Richmond (VA)
6               New Braunfels (TX)
7                Fayetteville (NC)
8                  Pittsburgh (PA)
9                 Devils Lake (ND)
10                     Quincy (FL)
11                     Queens (NY)
12                      Omaha (NE)
13              Muscle Shoals (AL)
14            Seabrook Island (SC)
15                 Hackensack (NJ)
16                  Morrilton (AR)
17                     Durham (NC)
18                           Dakar
19               Jacksonville (AR)
20                    Phoenix (AZ)
21                 Cincinnati (OH)
22                   Columbus (OH)
23                    Concord (CA)
24                  Dickinson (TX)
25                    Memphis (TN)
26           District Heights (MD)
27                Springfield (MO)
28                      Flint (MI)
29                    Roselle (NJ)
30               Fayetteville (AR)
31                Little Rock (AR)
32                  Tuscumbia (AL)
33             Mountain Brook (AL)
34                     Dallas (TX)
35                   Santo Domingo
36                  Charlotte (NC)
37              Muscle Shoals (AL)
38                  Alabaster (AL)
39                    Decatur (IL)
40                Shelbyville (TN)
41                  Knoxville (TN)
42               West Memphis (AR)
43               Fayetteville (AR)
44                    Nahunta (GA)
45                      Evans (GA)
46                     Dallas (TX)
47                Tallahassee (FL)
48                      Tampa (FL)
49             Mountain Brook (AL)
50                 New Market (AL)
51                   Mableton (GA)
52                 Boca Raton (FL)
53                    Sherman (TX)
54                 Washington (DC)
55              Pleasant Hill (CA)
56                   Fairburn (GA)
57                        Montreal
58                      Miami (FL)
59                 Colts Neck (NJ)
60                      Ocoee (FL)
61                       Frankfurt
62               Huntersville (NC)
63                          Kaunas
64                 New Oxford (PA)
65                    Orlando (FL)
66                      Tampa (FL)
67                 Lake Wales (FL)
68                           Perth
69                Short Hills (NJ)
70               Winter Haven (FL)
71                     Athens (GA)
72                     Dacula (GA)
73                   Richmond (TX)
74               Tinton Falls (NJ)
75                          Douala
76                Bay Village (OH)
77                  Knoxville (TN)
78                     Austin (TX)
79                         Vaughan
80          Fort Walton Beach (FL)
81                    Lilburn (GA)
82                Wake Forest (NC)
83                    Atlanta (GA)
84                    Arecibo (PR)
85                  Elizabeth (PA)
86                     Camden (NJ)
87                    Hickory (NC)
88                  Leetsdale (PA)
89                          Owerri
90                     London (KY)
91                    Phoenix (AZ)
92                   Not_Available
93                  Covington (KY)
94             St. Petersburg (FL)
95               Mt. Sterling (KY)
96                     Camden (NJ)
97                     Camden (NJ)
98                     Linton (IN)
99                   Florence (KY)
100              Philadelphia (PA)
101                Washington (DC)
102             Holly Springs (MS)
103               Baton Rouge (LA)
104                   Helotes (TX)
105                Mandeville (LA)
106                    Austin (TX)
107                 Las Vegas (NV)
108                    Austin (TX)
109                Hartsville (SC)
110               Baton Rouge (LA)
111               New Orleans (LA)
112                Cumberland (MD)
113                   Atlanta (TX)
114                    Walker (LA)
115                   Jackson (MS)
116                   Saginaw (MI)
117                     Coker (AL)
118             Bay St. Louis (MS)
119             Bowling Green (KY)
120                Greensboro (NC)
121                Birmingham (AL)
122                   Jackson (MS)
123                   Madison (MS)
124             Stephens City (VA)

In [ ]:
all_conferences_df["Home_State"] = all_conferences_df["Birth City"].apply(lambda x: x.split(" ")[-1])

In [ ]:
all_conferences_df["Home_State"] = all_conferences_df["Home_State"].apply(lambda x: x.strip("()"))

In [ ]:
all_conferences_df.School.nunique()

361

In [ ]:
all_conferences_df.head(10)

,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major,Home_State
0,0.0,175,Quinten Post,C,612,250.0,Boston College,Sr,"Mar 21, 2000",Amsterdam,NaN,ACC,High,Amsterdam
1,1.0,113,Chas Kelley III,G,605,180.0,Boston College,So,-,Houston (TX),Phelps Prep,ACC,High,TX
2,2.0,82,"Claudell Harris, Jr.",GF,603,190.0,Boston College,Jr,-,Hahnville (LA),Hahnville High School,ACC,High,LA
3,3.0,242,Jaeden Zackery,G,602,215.0,Boston College,Jr,-,Salem (WI),Westosha Central High School,ACC,High,WI
4,4.0,211,Elijah Strong,F,608,245.0,Boston College,Fr,-,Charlotte (NC),Myers Park High School,ACC,High,NC
5,5.0,171,Fred Payne,G,602,170.0,Boston College,Fr,-,Grambling (LA),Legacy the School of Sport Sciences,ACC,High,LA
6,6.0,102,Asher Jackson,G,605,205.0,Boston College,Fr,-,Mundelein (IL),Carmel Catholic High School,ACC,High,IL
7,7.0,51,Jack Di Donna,G,600,185.0,Boston College,Fr,-,Boca Raton (FL),Saint Andrew's School,ACC,High,FL
8,8.0,79,"Donald Hand, Jr.",GF,605,195.0,Boston College,Fr,-,Virginia Beach (VA),Landstown High School,ACC,High,VA
9,9.0,204,Ethan Soares,GF,604,225.0,Boston College,Fr,-,Houston (TX),Memorial High School,ACC,High,TX

In [ ]:
grouped_df = all_conferences_df.groupby(["Major", "Home_State"]).Player.count().reset_index()

In [ ]:
pivoted_df = grouped_df.pivot(columns = "Major", index = "Home_State", values = "Player")

In [ ]:
#print(pivoted_df.sort_values(by="High", ascending=False).to_string())

# California, Texas, and New York
Send the most players D1

In [ ]:
new_df.Home_State.value_counts()

CA             417
TX             409
NY             280
FL             260
GA             250
              ...
Durham           1
Kisumu           1
Springwater      1
Barahona         1
Debrecen         1
Name: Home_State, Length: 438, dtype: int64

# Separate First and Last Names

In [ ]:
all_conferences_df.Player.value_counts()

Jordan Johnson            3
Christian Moore           3
Braylon Jackson           2
Austin Williams           2
Josiah Harris             2
                         ..
Ra'Sean Frederick         1
Tyler Stephenson-Moore    1
Dean Noll                 1
Keenan Fitzmorris         1
Malik Olafioye            1
Name: Player, Length: 5738, dtype: int64

In [ ]:
all_conferences_df[(all_conferences_df.Player == "Christian Moore")]

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major,Home_State
1601,1601,Christian,Moore,Christian Moore,G,599,170.0,North Texas,So,-,Jacksonville (AR),Jacksonville High School,American,Mid,AR
3246,3246,Christian,Moore,Christian Moore,G,601,175.0,New Hampshire,So,-,Virginia Beach (VA),Hargrave Military Academy,AM_East,Low,VA
3980,3980,Christian,Moore,Christian Moore,GF,606,230.0,The Citadel,Fr,-,Los Angeles (CA),Avon Old Farms High School,Southern,Low,CA

In [ ]:
all_conferences_df["Unnamed: 0.1"] = all_conferences_df.Player.apply(lambda x: x.split(" ")[0])

In [ ]:
all_conferences_df["Last_Name"] = all_conferences_df.Player.apply(lambda x: x.split(" ")[1:] if (len(list(x.split(" "))) > 2) else x.split(" ")[-1])

In [ ]:
all_conferences_df["Last_Name"] = all_conferences_df.Player.apply(lambda x: "".join(x) if len(list(x)) > 1 else str(x))

In [ ]:
all_conferences_df["Last_Name"] = all_conferences_df.Last_Name.apply(lambda x: " ".join(x) if type(x) == list else x)

In [ ]:
all_conferences_df["Unnamed: 0.2"] = range(len(all_conferences_df))

In [ ]:
all_conferences_df.rename(columns = {"Unnamed: 0.2":"Reference", "Unnamed: 0.1":"First_Name", "Unnamed: 0":"Last_Name"}, inplace=True)

In [ ]:
all_conferences_df.head(50)

,Reference,First_Name,Last_Name,Player,Pos,HT,WT,School,Class,Birth Date,Birth City,High School/Prep School,Conference,Major,Home_State
0,0,Quinten,Post,Quinten Post,C,612,250.0,Boston College,Sr,21-Mar-00,Amsterdam,NaN,ACC,High,Amsterdam
1,1,Chas,Kelley III,Chas Kelley III,G,605,180.0,Boston College,So,-,Houston (TX),Phelps Prep,ACC,High,TX
2,2,Claudell,"Harris, Jr.","Claudell Harris, Jr.",GF,603,190.0,Boston College,Jr,-,Hahnville (LA),Hahnville High School,ACC,High,LA
3,3,Jaeden,Zackery,Jaeden Zackery,G,602,215.0,Boston College,Jr,-,Salem (WI),Westosha Central High School,ACC,High,WI
4,4,Elijah,Strong,Elijah Strong,F,608,245.0,Boston College,Fr,-,Charlotte (NC),Myers Park High School,ACC,High,NC
5,5,Fred,Payne,Fred Payne,G,602,170.0,Boston College,Fr,-,Grambling (LA),Legacy the School of Sport Sciences,ACC,High,LA
6,6,Asher,Jackson,Asher Jackson,G,605,205.0,Boston College,Fr,-,Mundelein (IL),Carmel Catholic High School,ACC,High,IL
7,7,Jack,Di Donna,Jack Di Donna,G,600,185.0,Boston College,Fr,-,Boca Raton (FL),Saint Andrew's School,ACC,High,FL
8,8,Donald,"Hand, Jr.","Donald Hand, Jr.",GF,605,195.0,Boston College,Fr,-,Virginia Beach (VA),Landstown High School,ACC,High,VA
9,9,Ethan,Soares,Ethan Soares,GF,604,225.0,Boston College,Fr,-,Houston (TX),Memorial High School,ACC,High,TX
10,10,Armani,Mighty,Armani Mighty,C,610,225.0,Boston College,So,-,Thornhill,United Scholastic Academy,ACC,High,Thornhill
11,11,Mason,Madsen,Mason Madsen,G,604,195.0,Boston College,Sr,1-May-01,Rochester (MN),Mayo High School,ACC,High,MN
12,12,Abe,Atiyeh,Abe Atiyeh,G,600,195.0,Boston College,Sr,-,Bethlehem (PA),Moravian Academy,ACC,High,PA
13,13,Jayden,Hastings,Jayden Hastings,FC,609,225.0,Boston College,Fr,-,Orlando (FL),IMG Academy,ACC,High,FL
14,14,Prince,Aligbe,Prince Aligbe,F,607,225.0,Boston College,So,-,Minneapolis (MN),Minnehaha Academy,ACC,High,MN
15,15,Devin,McGlockton,Devin McGlockton,F,607,215.0,Boston College,Jr,-,Cumming (GA),South Forsyth High School,ACC,High,GA
16,16,Jack,Clark,Jack Clark,F,608,200.0,Clemson,Sr,14-Feb-00,Wyncote (PA),Cheltenham High School,ACC,High,PA
17,17,P.J.,Hall,P.J. Hall,PF,610,245.0,Clemson,Sr,21-Feb-02,Roebuck (SC),Dorman High School,ACC,High,SC
18,18,Chase,Hunter,Chase Hunter,SG,604,204.0,Clemson,Sr,8-Apr-01,Atlanta (GA),Westlake High School,ACC,High,GA
19,19,Asa,Thomas,Asa Thomas,F,607,185.0,Clemson,Fr,-,Lake Forest (IL),Lake Forest High School,ACC,High,IL
20,20,Dillon,Hunter,Dillon Hunter,GF,604,193.0,Clemson,So,16-Apr-03,Atlanta (GA),Sunrise Christian Academy,ACC,High,GA
21,21,Jake,Heidbreder,Jake Heidbreder,PG,605,180.0,Clemson,Jr,-,Floyds Knobs (IN),Floyd Central High School,ACC,High,IN
22,22,Alex,Hemenway,Alex Hemenway,SG,604,195.0,Clemson,Sr,17-Jun-01,Newburgh (IN),Castle High School,ACC,High,IN
23,23,Matt,Kelly,Matt Kelly,G,601,172.0,Clemson,So,-,Charleston (SC),Porter-Gaud High School,ACC,High,SC
24,24,Joseph,Girard III,Joseph Girard III,G,601,190.0,Clemson,Sr,27-Nov-00,Glen Falls (NY),Glen Falls High School,ACC,High,NY
25,25,Daniel,Nauseef,Daniel Nauseef,F,607,215.0,Clemson,Jr,-,Dayton (OH),Chaminade-Julienne High School,ACC,High,OH
26,26,Andrew,Latiff,Andrew Latiff,GF,604,175.0,Clemson,Sr,-,Clemson (SC),NaN,ACC,High,SC
27,27,Ian,Schieffelin,Ian Schieffelin,F,607,230.0,Clemson,Jr,-,Grayson (GA),Grayson High School,ACC,High,GA
28,28,Chauncey,Wiggins,Chauncey Wiggins,C,610,205.0,Clemson,So,-,Loganville (GA),Grayson High School,ACC,High,GA
29,29,Bas,Leyte,Bas Leyte,PF,610,220.0,Clemson,Sr,4-Apr-01,Bergen,New Hampton School,ACC,High,Bergen
30,30,Josh,Beadle,Josh Beadle,G,603,182.0,Clemson,So,-,Columbia (SC),Cardinal Newman High School,ACC,High,SC
31,31,R.J.,Godfrey,R.J. Godfrey,F,607,225.0,Clemson,So,-,Suwanee (GA),North Gwinnett High School,ACC,High,GA
32,32,Tyrese,Proctor,Tyrese Proctor,PG,605,183.0,Duke,So,1-Apr-04,Sydney,NBA Global Academy,ACC,High,Sydney
33,33,Jaden,Schutt,Jaden Schutt,G,605,190.0,Duke,So,20-Apr-03,Yorkville (IL),Yorkville High School,ACC,High,IL
34,34,T.J.,Power,T.J. Power,F,609,216.0,Duke,Fr,23-Sep-03,Shrewsbury (MA),Worcester Academy,ACC,High,MA
35,35,Christian,Reeves,Christian Reeves,C,613,261.0,Duke,So,14-Dec-03,Charlotte (NC),Oak Hill Academy,ACC,High,NC
36,36,Jared,McCain,Jared McCain,G,603,197.0,Duke,Fr,20-Feb-04,Corona (CA),Centennial High School,ACC,High,CA
37,37,Caleb,Foster,Caleb Foster,G,605,197.0,Duke,Fr,16-Jul-04,Yanceyville (NC),Notre Dame High School,ACC,High,NC
38,38,Spencer,Hubbard,Spencer Hubbard,G,596,157.0,Duke,Sr,30-Apr-01,Studio City (CA),Harvard-Westlake School,ACC,High,CA
39,39,Jeremy,Roach,Jeremy Roach,G,602,180.0,Duke,Sr,1-Nov-01,Leesburg (VA),Paul VI Catholic High School,ACC,High,VA
40,40,Kyle,Filipowski,Kyle Filipowski,C,612,248.0,Duke,So,7-Nov-03,Middletown (NY),Wilbraham & Monson Academy,ACC,High,NY
41,41,Ryan,Young,Ryan Young,PF,610,238.0,Duke,Sr,2-Dec-99,Montreal,Bethlehem Catholic High School,ACC,High,Montreal
42,42,Neal,Begovich,Neal Begovich,F,609,230.0,Duke,Sr,-,San Francisco (CA),St. Ignatius College Prep,ACC,High,CA
43,43,Stanley,Borden,Stanley Borden,C,612,241.0,Duke,Jr,7-Oct-02,Istanbul,NaN,ACC,High,Istanbul
44,44,Sean,Stewart,Sean Stewart,F,609,227.0,Duke,Fr,17-Feb-05,Orlando (FL),Montverde Academy,ACC,High,FL
45,45,Jaylen,Blakes,Jaylen Blakes,G,602,204.0,Duke,Jr,7-Apr-03,Somerset (NJ),Blair Academy,ACC,High,NJ
46,46,Mark,"Mitchell, Jr.","Mark Mitchell, Jr.",SF,609,232.0,Duke,So,1-Sep-03,Lansing (KS),Sunrise Christian Academy,ACC,High,KS
47,47,Tom,House,Tom House,F,607,200.0,Florida State,So,10-Nov-03,Centerville (OH),Centerville High School,ACC,High,OH
48,48,Cam'Ron,Fletcher,Cam'Ron Fletcher,PF,607,220.0,Florida State,Sr,10-Jul-01,St. Louis (MO),Vashon High School,ACC,High,MO
49,49,Jaylan,Gainey,Jaylan Gainey,F,610,220.0,Florida State,Sr,12-Dec-99,Greensboro (NC),Academy At Smith High School,ACC,High,NC

In [ ]:
type(all_conferences_df.Last_Name[1])

list

In [ ]:
all_conferences_df.to_csv("All_Conferences_Great_Job.csv")

In [ ]:
school_locations = pd.read_html("https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_institutions")

In [ ]:
school_df = school_locations[1]

In [ ]:
school_df.head(50)

,School,Common Name,Nickname,City,State,Type,Subdivision,Primary Conference
0,Abilene Christian University,Abilene Christian,Wildcats,Abilene,TX,Private,FCS,Western Athletic Conference[a]
1,Alabama Agricultural and Mechanical University,Alabama A&M,Bulldogs[h],Normal,AL,Public,FCS,Southwestern Athletic Conference
2,Alabama State University,Alabama State,Hornets[i],Montgomery,AL,Public,FCS,Southwestern Athletic Conference
3,Alcorn State University,Alcorn State,Braves[j],Lorman,MS,Public,FCS,Southwestern Athletic Conference
4,American University,American,Eagles,Washington,DC,Private,Non-football,Patriot League
5,Appalachian State University,Appalachian State,Mountaineers,Boone,NC,Public,FBS,Sun Belt Conference
6,Arizona State University,Arizona State,Sun Devils,Tempe[b],AZ,Public,FBS,Pac-12 Conference[c]
7,Arkansas State University,Arkansas State,Red Wolves,Jonesboro,AR,Public,FBS,Sun Belt Conference
8,Auburn University,Auburn,Tigers,Auburn,AL,Public,FBS,Southeastern Conference
9,Austin Peay State University,Austin Peay,Governors,Clarksville,TN,Public,FCS,Atlantic Sun Conference[a]
10,Ball State University,Ball State,Cardinals,Muncie,IN,Public,FBS,Mid-American Conference
11,Baylor University,Baylor,Bears,Waco,TX,Private,FBS,Big 12 Conference
12,Belmont University,Belmont,Bruins,Nashville,TN,Private,Non-football,Missouri Valley Conference
13,Bethune–Cookman University,Bethune–Cookman,Wildcats,Daytona Beach,FL,Private,FCS,Southwestern Athletic Conference
14,Boise State University,Boise State,Broncos,Boise,ID,Public,FBS,Mountain West Conference
15,Boston College,Boston College,Eagles,Chestnut Hill,MA,Private,FBS,Atlantic Coast Conference
16,Boston University,Boston University,Terriers,Boston,MA,Private,Non-football,Patriot League
17,Bowling Green State University,Bowling Green,Falcons,Bowling Green,OH,Public,FBS,Mid-American Conference
18,Bradley University,Bradley,Braves,Peoria,IL,Private,Non-football,Missouri Valley Conference
19,Brigham Young University,BYU,Cougars,Provo,UT,Private,FBS,Big 12 Conference
20,Brown University,Brown,Bears,Providence,RI,Private,FCS,Ivy League
21,Bryant University,Bryant,Bulldogs,Smithfield,RI,Private,FCS,America East Conference[d]
22,Bucknell University,Bucknell,Bison,Lewisburg,PA,Private,FCS,Patriot League
23,Butler University,Butler,Bulldogs,Indianapolis,IN,Private,FCS,Big East Conference[e]
24,California Baptist University,Cal Baptist,Lancers,Riverside,CA,Private,Non-football,Western Athletic Conference
25,California Polytechnic State University,Cal Poly,Mustangs,San Luis Obispo,CA,Public,FCS,Big West Conference[f]
26,"California State University, Bakersfield",Bakersfield[g],Roadrunners,Bakersfield,CA,Public,Non-football,Big West Conference
27,"California State University, Fresno",Fresno State,Bulldogs,Fresno,CA,Public,FBS,Mountain West Conference
28,"California State University, Fullerton",Cal State Fullerton,Titans,Fullerton,CA,Public,Non-football,Big West Conference
29,"California State University, Long Beach",Long Beach State,Beach,Long Beach,CA,Public,Non-football,Big West Conference
30,"California State University, Northridge",Cal State Northridge,Matadors,Northridge,CA,Public,Non-football,Big West Conference
31,"California State University, Sacramento",Sacramento State,Hornets,Sacramento,CA,Public,FCS,Big Sky Conference
32,Campbell University,Campbell,Fighting Camels,Buies Creek,NC,Private,FCS,Coastal Athletic Association[h]
33,Canisius University,Canisius,Golden Griffins,Buffalo,NY,Private,Non-football,Metro Atlantic Athletic Conference
34,Central Connecticut State University,Central Connecticut,Blue Devils,New Britain,CT,Public,FCS,Northeast Conference
35,Central Michigan University,Central Michigan,Chippewas,Mount Pleasant,MI,Public,FBS,Mid-American Conference
36,Charleston Southern University,Charleston Southern,Buccaneers,North Charleston,SC,Private,FCS,Big South Conference
37,Chicago State University,Chicago State,Cougars,Chicago,IL,Public,Non-football,Independent[i]
38,Clemson University,Clemson,Tigers,Clemson,SC,Public,FBS,Atlantic Coast Conference
39,Cleveland State University,Cleveland State,Vikings,Cleveland,OH,Public,Non-football,Horizon League
40,Coastal Carolina University,Coastal Carolina,Chanticleers,Conway,SC,Public,FBS,Sun Belt Conference
41,Colgate University,Colgate,Raiders,Hamilton,NY,Private,FCS,Patriot League
42,College of Charleston,Charleston[j],Cougars,Charleston,SC,Public,Non-football,Coastal Athletic Association
43,College of the Holy Cross,Holy Cross,Crusaders,Worcester,MA,Private,FCS,Patriot League
44,Colorado State University,Colorado State,Rams,Fort Collins,CO,Public,FBS,Mountain West Conference
45,Columbia University in the City of New York,Columbia,Lions,New York,NY,Private,FCS,Ivy League
46,Coppin State University,Coppin State,Eagles,Baltimore,MD,Public,Non-football,Mid-Eastern Athletic Conference
47,Cornell University,Cornell,Big Red,Ithaca,NY,Private,FCS,Ivy League
48,Creighton University,Creighton,Bluejays,Omaha,NE,Private,Non-football,Big East Conference
49,Dartmouth College,Dartmouth,Big Green,Hanover,NH,Private,FCS,Ivy League

In [ ]:
school_df[(school_df)]

if all_conferences_df.School ==

pd.Merge(all_conferences_df, school_df, how="left", axis = 1)

In [ ]:
side_by_side = pd.concat([all_conferences_df, school_df], axis =1)

In [ ]:
side_by_side.head()

,Reference,First_Name,Last_Name,Player,Pos,HT,WT,School,Class,Birth Date,...,Major,Home_State,School,Common Name,Nickname,City,State,Type,Subdivision,Primary Conference
0,0,Quinten,Post,Quinten Post,C,612,250.0,Boston College,Sr,21-Mar-00,...,High,Amsterdam,Abilene Christian University,Abilene Christian,Wildcats,Abilene,TX,Private,FCS,Western Athletic Conference[a]
1,1,Chas,Kelley III,Chas Kelley III,G,605,180.0,Boston College,So,-,...,High,TX,Alabama Agricultural and Mechanical University,Alabama A&M,Bulldogs[h],Normal,AL,Public,FCS,Southwestern Athletic Conference
2,2,Claudell,"Harris, Jr.","Claudell Harris, Jr.",GF,603,190.0,Boston College,Jr,-,...,High,LA,Alabama State University,Alabama State,Hornets[i],Montgomery,AL,Public,FCS,Southwestern Athletic Conference
3,3,Jaeden,Zackery,Jaeden Zackery,G,602,215.0,Boston College,Jr,-,...,High,WI,Alcorn State University,Alcorn State,Braves[j],Lorman,MS,Public,FCS,Southwestern Athletic Conference
4,4,Elijah,Strong,Elijah Strong,F,608,245.0,Boston College,Fr,-,...,High,NC,American University,American,Eagles,Washington,DC,Private,Non-football,Patriot League

In [ ]:
test_merge = pd.merge(all_conferences_df, school_df, how = "left", left_on ="School", right_on = "Common Name")

In [ ]:
test_merge.head()

,Reference,First_Name,Last_Name,Player,Pos,HT,WT,School_x,Class,Birth Date,...,Major,Home_State,School_y,Common Name,Nickname,City,State,Type,Subdivision,Primary Conference
0,0,Quinten,Post,Quinten Post,C,612,250.0,Boston College,Sr,21-Mar-00,...,High,Amsterdam,Boston College,Boston College,Eagles,Chestnut Hill,MA,Private,FBS,Atlantic Coast Conference
1,1,Chas,Kelley III,Chas Kelley III,G,605,180.0,Boston College,So,-,...,High,TX,Boston College,Boston College,Eagles,Chestnut Hill,MA,Private,FBS,Atlantic Coast Conference
2,2,Claudell,"Harris, Jr.","Claudell Harris, Jr.",GF,603,190.0,Boston College,Jr,-,...,High,LA,Boston College,Boston College,Eagles,Chestnut Hill,MA,Private,FBS,Atlantic Coast Conference
3,3,Jaeden,Zackery,Jaeden Zackery,G,602,215.0,Boston College,Jr,-,...,High,WI,Boston College,Boston College,Eagles,Chestnut Hill,MA,Private,FBS,Atlantic Coast Conference
4,4,Elijah,Strong,Elijah Strong,F,608,245.0,Boston College,Fr,-,...,High,NC,Boston College,Boston College,Eagles,Chestnut Hill,MA,Private,FBS,Atlantic Coast Conference

In [ ]:
test_merge.to_csv("test_merge.csv")

In [ ]:
school_df.to_csv("School_Details.csv")

In [ ]:
import pandas as pd

In [ ]:
new_df = pd.read_csv("All_Conferences_Details_Merged.csv", encoding = "ISO-8859-1")

In [ ]:
new_df.head()

,Unnamed: 0,Reference,First_Name,Last_Name,Player,Pos,HT,WT,Class,Birth Date,...,Conference_Official_Name,Major,Mascot,School_City,School_State,Public_Private,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,0,0,Quinten,Post,Quinten Post,C,612,250.0,Sr,21-Mar-00,...,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,NaN,NaN,NaN,NaN
1,1,1,Chas,Kelley III,Chas Kelley III,G,605,180.0,So,-,...,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,NaN,NaN,NaN,NaN
2,2,2,Claudell,"Harris, Jr.","Claudell Harris, Jr.",GF,603,190.0,Jr,-,...,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,NaN,NaN,NaN,NaN
3,3,3,Jaeden,Zackery,Jaeden Zackery,G,602,215.0,Jr,-,...,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,NaN,NaN,NaN,NaN
4,4,4,Elijah,Strong,Elijah Strong,F,608,245.0,Fr,-,...,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,NaN,NaN,NaN,NaN

25% of D1 Players go to schools in their home state

In [ ]:
new_df[(new_df.Home_State == new_df.School_State)]

,Unnamed: 0,Reference,First_Name,Last_Name,Player,Pos,HT,WT,Class,Birth Date,...,Conference_Official_Name,Major,Mascot,School_City,School_State,Public_Private,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
17,17,17,P.J.,Hall,P.J. Hall,PF,610,245.0,Sr,21-Feb-02,...,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,NaN,NaN,NaN,NaN
23,23,23,Matt,Kelly,Matt Kelly,G,601,172.0,So,-,...,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,NaN,NaN,NaN,NaN
26,26,26,Andrew,Latiff,Andrew Latiff,GF,604,175.0,Sr,-,...,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,NaN,NaN,NaN,NaN
30,30,30,Josh,Beadle,Josh Beadle,G,603,182.0,So,-,...,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,NaN,NaN,NaN,NaN
35,35,35,Christian,Reeves,Christian Reeves,C,613,261.0,So,14-Dec-03,...,Atlantic Coast Conference,High,Blue Devils,Durham,NC,Private,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5751,5751,5751,Adam,Tauer,Adam Tauer,SF,603,175.0,Fr,-,...,Summit League[ac],Low,Tommies,Saint Paul,MN,Private,NaN,NaN,NaN,NaN
5753,5753,5753,Courtney,"Brown, Jr.","Courtney Brown, Jr.",F,607,215.0,Sr,20-Sep-01,...,Summit League[ac],Low,Tommies,Saint Paul,MN,Private,NaN,NaN,NaN,NaN
5754,5754,5754,Carter,Bjerke,Carter Bjerke,F,609,250.0,Fr,-,...,Summit League[ac],Low,Tommies,Saint Paul,MN,Private,NaN,NaN,NaN,NaN
5756,5756,5756,Hayden,Tibbits,Hayden Tibbits,G,599,165.0,Fr,-,...,Summit League[ac],Low,Tommies,Saint Paul,MN,Private,NaN,NaN,NaN,NaN
5757,5757,5757,Brooks,Allen,Brooks Allen,F,607,210.0,Sr,-,...,Summit League[ac],Low,Tommies,Saint Paul,MN,Private,NaN,NaN,NaN,NaN

In [ ]:
new_df.shape

(5777, 27)

In [ ]:
round(1500/5777 * 100,2)

25.97

In [ ]:
new_df["In_State"] = new_df.apply(lambda x: True if (x.Home_State == x.School_State) else False, axis=1)

In [ ]:
new_df_copy = new_df

In [ ]:
new_df.drop(columns = ["Unnamed: 0"], inplace=True)

In [ ]:
new_df.drop(columns = ["Unnamed: 23","Unnamed: 24","Unnamed: 25","Unnamed: 26"], inplace=True)

In [ ]:
new_df.head(30)

,Reference,First_Name,Last_Name,Player,Pos,HT,WT,Class,Birth Date,Birth City,...,School,School_Official_Name,Conference,Conference_Official_Name,Major,Mascot,School_City,School_State,Public_Private,In_State
0,0,Quinten,Post,Quinten Post,C,612,250.0,Sr,21-Mar-00,Amsterdam,...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
1,1,Chas,Kelley III,Chas Kelley III,G,605,180.0,So,-,Houston (TX),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
2,2,Claudell,"Harris, Jr.","Claudell Harris, Jr.",GF,603,190.0,Jr,-,Hahnville (LA),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
3,3,Jaeden,Zackery,Jaeden Zackery,G,602,215.0,Jr,-,Salem (WI),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
4,4,Elijah,Strong,Elijah Strong,F,608,245.0,Fr,-,Charlotte (NC),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
5,5,Fred,Payne,Fred Payne,G,602,170.0,Fr,-,Grambling (LA),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
6,6,Asher,Jackson,Asher Jackson,G,605,205.0,Fr,-,Mundelein (IL),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
7,7,Jack,Di Donna,Jack Di Donna,G,600,185.0,Fr,-,Boca Raton (FL),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
8,8,Donald,"Hand, Jr.","Donald Hand, Jr.",GF,605,195.0,Fr,-,Virginia Beach (VA),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
9,9,Ethan,Soares,Ethan Soares,GF,604,225.0,Fr,-,Houston (TX),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
10,10,Armani,Mighty,Armani Mighty,C,610,225.0,So,-,Thornhill,...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
11,11,Mason,Madsen,Mason Madsen,G,604,195.0,Sr,1-May-01,Rochester (MN),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
12,12,Abe,Atiyeh,Abe Atiyeh,G,600,195.0,Sr,-,Bethlehem (PA),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
13,13,Jayden,Hastings,Jayden Hastings,FC,609,225.0,Fr,-,Orlando (FL),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
14,14,Prince,Aligbe,Prince Aligbe,F,607,225.0,So,-,Minneapolis (MN),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
15,15,Devin,McGlockton,Devin McGlockton,F,607,215.0,Jr,-,Cumming (GA),...,Boston College,Boston College,ACC,Atlantic Coast Conference,High,Eagles,Chestnut Hill,MA,Private,False
16,16,Jack,Clark,Jack Clark,F,608,200.0,Sr,14-Feb-00,Wyncote (PA),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
17,17,P.J.,Hall,P.J. Hall,PF,610,245.0,Sr,21-Feb-02,Roebuck (SC),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,True
18,18,Chase,Hunter,Chase Hunter,SG,604,204.0,Sr,8-Apr-01,Atlanta (GA),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
19,19,Asa,Thomas,Asa Thomas,F,607,185.0,Fr,-,Lake Forest (IL),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
20,20,Dillon,Hunter,Dillon Hunter,GF,604,193.0,So,16-Apr-03,Atlanta (GA),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
21,21,Jake,Heidbreder,Jake Heidbreder,PG,605,180.0,Jr,-,Floyds Knobs (IN),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
22,22,Alex,Hemenway,Alex Hemenway,SG,604,195.0,Sr,17-Jun-01,Newburgh (IN),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
23,23,Matt,Kelly,Matt Kelly,G,601,172.0,So,-,Charleston (SC),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,True
24,24,Joseph,Girard III,Joseph Girard III,G,601,190.0,Sr,27-Nov-00,Glen Falls (NY),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
25,25,Daniel,Nauseef,Daniel Nauseef,F,607,215.0,Jr,-,Dayton (OH),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
26,26,Andrew,Latiff,Andrew Latiff,GF,604,175.0,Sr,-,Clemson (SC),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,True
27,27,Ian,Schieffelin,Ian Schieffelin,F,607,230.0,Jr,-,Grayson (GA),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
28,28,Chauncey,Wiggins,Chauncey Wiggins,C,610,205.0,So,-,Loganville (GA),...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False
29,29,Bas,Leyte,Bas Leyte,PF,610,220.0,Sr,4-Apr-01,Bergen,...,Clemson,Clemson University,ACC,Atlantic Coast Conference,High,Tigers,Clemson,SC,Public,False

In [ ]:
new_df.In_State.value_counts()[1]/ new_df.In_State.value_counts().sum()

0.2596503375454388

In [ ]:
new_df.Player.value_counts()

Jordan Johnson            3
Christian Moore           3
Braylon Jackson           2
Austin Williams           2
Josiah Harris             2
                         ..
Ra'Sean Frederick         1
Tyler Stephenson-Moore    1
Dean Noll                 1
Keenan Fitzmorris         1
Malik Olafioye            1
Name: Player, Length: 5738, dtype: int64

In [ ]:
new_df.to_csv("College_Basketball.csv")

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
website_html = requests.get("https://www.nba.com/stats/team/1610612752/traditional?PerMode=PerGame")

In [ ]:
website_html.status_code

200